### PR TITLE
Complete TaskID4 tasks, add exception handle

### LINKED ISSUE #4: Implement a function that creates the correct sized array based off the game mode:
int[] mode1 = new array[10]
int[] mode2 = new array[1000]
int[] mode3 = new array[100]

TASK ID: 4

### PR DESCRIPTION
**Pull request by Virtruvian1**
Review TaskID4 before commit to master branch

### CODE REVIEW

File: GuessMyNumberGame/Program.cs [hunk 1]
```diff
@@ -11,28 +11,37 @@ namespace GuessMyNumberGame
     class GameEngine
     {
         private byte _gameMode;
+        public int[] gameArray;
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:14]: Created global variable to store the created array

File: GuessMyNumberGame/Program.cs [hunk 2]
```diff
@@ -1,4 +1,4 @@
-﻿using System;
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:1]: No change

File: GuessMyNumberGame/Program.cs [hunk 3]
```diff
@@ -11,28 +11,37 @@ namespace GuessMyNumberGame
...
         private byte _gameMode;
+        public int[] gameArray;
 
         public GameEngine() // Default Constructor
         {
             _gameMode = 0;
         }
         public byte GameMode // Set _gameMode
         {
-            get { return _gameMode;  }
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:21]: Deleted a space

File: GuessMyNumberGame/Program.cs [hunk 4]
```diff
@@ -11,28 +11,37 @@ namespace GuessMyNumberGame
...
+            get { return _gameMode; }
             set
             {
                 if (value >= 1 && value <= 3)
                 {
                     _gameMode = value;
                 }
-                while (!(_gameMode == 1 || _gameMode == 2 || _gameMode == 3))
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:28]: No change

File: GuessMyNumberGame/Program.cs [hunk 5]
```diff
@@ -11,28 +11,37 @@ namespace GuessMyNumberGame
...
                     _gameMode = value;
                 }
-                while (!(_gameMode == 1 || _gameMode == 2 || _gameMode == 3)) 
+                while (!(_gameMode == 1 || _gameMode == 2 || _gameMode == 3))
                 {
-                    Console.Write("Please Enter a valid Game Mode [ 1, 2, 3 ]:\r\n" +
-                                  "(Please type your answer) Input: ");
-                    byte userInput = Convert.ToByte(Console.ReadLine());
-                    if (userInput >= 1 && userInput <= 3)
+                    try
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:31]: Added exception handling if user inputs numbers outside of a byte

File: GuessMyNumberGame/Program.cs [hunk 6]
```diff
@@ -11,28 +11,37 @@ namespace GuessMyNumberGame
...
+                        Console.Clear();
+                        Console.Write("Please Enter a valid Game Mode [ 1, 2, 3 ]:\r\n" +
+                                      "(Please type your answer) Input: ");
+                        byte userInput = Convert.ToByte(Console.ReadLine());
+                        if (userInput >= 1 && userInput <= 3)
+                        {
+                            _gameMode = userInput;
+                        }
+                    }
+                    catch (Exception)
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:42]: Catch for the try block

File: GuessMyNumberGame/Program.cs [hunk 7]
```diff
@@ -11,28 +11,37 @@ namespace GuessMyNumberGame
...
-                    byte userInput = Convert.ToByte(Console.ReadLine());
-                    if (userInput >= 1 && userInput <= 3)
+                    try
                     {
-                        _gameMode = userInput;
+                        Console.Clear();
+                        Console.Write("Please Enter a valid Game Mode [ 1, 2, 3 ]:\r\n" +
+                                      "(Please type your answer) Input: ");
+                        byte userInput = Convert.ToByte(Console.ReadLine());
+                        if (userInput >= 1 && userInput <= 3)
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:37]: Writes to _gameMode if the input is correct

File: GuessMyNumberGame/Program.cs [hunk 8]
```diff
@@ -41,21 +50,48 @@ public void GetGameMode()
...
-                            "Mode 1: Can you guess the right number 1 to 10?\r\n\r\n" +
-                            "Mode 2: Can you guess the right number 1 to 1000?\r\n\r\n" +
-                            "Mode 3: Can the computer guess your number 1 to 100?\r\n\r\n" +
-                            "(Please type your answer) Input: ");
-            GameMode = Convert.ToByte(Console.ReadLine());
+                          "Mode 1: Can you guess the right number 1 to 10?\r\n\r\n" +
+                          "Mode 2: Can you guess the right number 1 to 1000?\r\n\r\n" +
+                          "Mode 3: Can the computer guess your number 1 to 100?\r\n\r\n" +
+                          "(Please type your answer) Input: ");
+            try { GameMode = Convert.ToByte(Console.ReadLine()); }
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:57]: Added exception handling

File: GuessMyNumberGame/Program.cs [hunk 9]
```diff
@@ -41,21 +50,48 @@ public void GetGameMode()
...
+            catch (Exception) { };
         }
-        
+        public void CreateArray()
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:60]: Creates the correct sized array based on the correct game mode

File: GuessMyNumberGame/Program.cs [hunk 10]
```diff
@@ -41,21 +50,48 @@ public void GetGameMode()
...
+                    gameArray = gameArray2;
+                    break;
+                case 3:
+                    int[] gameArray3 = new int[100];
+                    gameArray = gameArray3;
+                    break;
+                default:
+                    break;
+            }
+            for (int i = 0; i < gameArray.Length; i++)
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:80]: Writes the incremental values to the created array

File: GuessMyNumberGame/Program.cs [hunk 11]
```diff
@@ -41,21 +50,48 @@ public void GetGameMode()
...
 
     class Program
     {
         static void Main(string[] args)
         {
-            GameEngine Start = new GameEngine();
-            Start.GetGameMode();
+            GameEngine Game = new GameEngine();
+            Game.GetGameMode();
+            Game.CreateArray();
```
Comment (Virtruvian1) [inline GuessMyNumberGame/Program.cs:94]: Added to main
